version: 2

models:
  - name: dim_patients
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique

  - name: dim_conditions_all
    columns:
      - name: sctid
        tests:
          - not_null
          - unique
      - name: description
        tests:
          - not_null
          - unique
